import pandas as pd

data = {
        "Movie":["KGF", "KGF", "KGF", "Pushpa", "Pushpa", "Pushpa",
                 "Dangal", "Dangal", "Dangal", "Jawan", "Jawan", "Jawan"],
        "Genre": ["Action", "Action", "Action", "Action", "Action", "Action",
                  "Drama", "Drama", "Drama", "Action", "Action", "Action"],
        "Platform": ["Netflix", "Amazon", "Hotstar", "Netflix", "Amazon", "Hotstar",
                     "Netflix", "Amazon", "Hotstar", "Netflix", "Amazon", "Hotstar"],
        "Year":[2022, 2022, 2022, 2023, 2023, 2023,
                2021, 2021, 2021, 2023, 2023, 2023],
        "Views Millions":[25, 20, 15,
                          30, 22, 18,
                          28, 24, 19,
                          35, 26, 21],
       "Revenue_Lakhs": [500, 420, 350,
                         600, 480, 390,
                         550, 460, 370,
                         700, 520, 410]
}

df = pd.DataFrame(data)
print(df)

# pivot1 = pd.pivot_table(
#     df,
#     values="Revenue_Lakhs",
#     index="Movie",
#     aggfunc="sum",
# )
# print(pivot1)

# Total revenue generated by each Movie
pivot1 = pd.pivot_table(
    df,
    index="Movie",
    values="Revenue_Lakhs",
    aggfunc="sum",
)
print(pivot1)

# Total views generated by each Platform
pivot2 = pd.pivot_table(
    df,
    index="Platform",
    values="Views Millions",
    aggfunc="sum",
)
print(pivot2)

# Average revenue per Genre
pivot3 = pd.pivot_table(
    df,
    index="Genre",
    values="Revenue_Lakhs",
    aggfunc="mean",
)
print(pivot3)

# Total revenue per Year
pivot4 = pd.pivot_table(
    df,
    index="Year",
    values="Revenue_Lakhs",
    aggfunc="sum",
)
print(pivot4)


# Total views for each Genre
pivot5 = pd.pivot_table(
    df,
    index="Genre",
    values="Views Millions",
    aggfunc="sum",
)
print(pivot5)

# Printing one example to show the format
print(pivot5)

# Sort by Revenue in descending order
pivot6 = pd.pivot_table(
    df,
    index="Movie",
    values="Revenue_Lakhs",
    aggfunc="sum",
)

sorted_revenue = pivot6.sort_values("Revenue_Lakhs", ascending=False)
print(f"Movies Ranked by Total Revenue  :\n{sorted_revenue}")

# Sort platforms by total views in ascending order
pivot7 = pd.pivot_table(
    df,
    index="Platform",
    values="Views Millions",
    aggfunc="sum",
)
sort_val = pivot7.sort_values("Views Millions",ascending=True)
print(sort_val)

#Find top 3 highest revenue-generating movies
pivot8 = pd.pivot_table(
    df,
    index="Movie",
    values="Revenue_Lakhs",
    aggfunc="sum"
).sort_values("Revenue_Lakhs", ascending=False).head(3)


#Find bottom 2 movies based on total views
pivot9 = pd.pivot_table(
    df,
    index="Movie",
    values="Views Millions",
    aggfunc="sum"
).sort_values("Views Millions", ascending=True).head(2)
print(pivot9)

#Sort genres by average revenue (highest first)
pivot10 = pd.pivot_table(
    df,
    index="Genre",
    values="Revenue_Lakhs",
    aggfunc="mean"
).sort_values("Revenue_Lakhs", ascending=False)
print(pivot10)

# Create a pivot table showing reveenue by platform and enre
pivot11 = pd.pivot_table(
    df,
    values="Revenue_Lakhs",
    index="Platform",
    columns="Genre",
    aggfunc="sum",
)
print(pivot11)

# Create a pivot table showing total views ny year and platform
pivot12 = pd.pivot_table(
    df,
    values="Views Millions",
    index="Year",
    columns="Platform"
)
print(pivot12)

# pivot table for showing average revenue by genre and year
pivot13 = round(pd.pivot_table(
    df,
    values="Revenue_Lakhs",
    index="Year",
    columns="Genre",
    aggfunc="mean",
    fill_value=0
),2)
print(pivot13)

# Create a pivot table showing revenue by Movie and Platform with margins.
pivot14 = pd.pivot_table(
    df,
    values="Revenue_Lakhs",
    index="Movie",
    columns="Platform",
    margins=True,
)
print(pivot14)

# Sum and Mean Revenue per Platform
print("\n Sum and Mean Revenue per Platform")
pivot15 = pd.pivot_table(
    df,
    values="Revenue_Lakhs",
    index="Platform",
    aggfunc=["sum", "mean"]
)
print(pivot15)

# Create a pivot table with index as (Movie, Platform) and calculate total revenue.
pivot16 = pd.pivot_table(
    df,
    values="Revenue_Lakhs",
    index=["Movie","Platform"],
    aggfunc="sum",
    margins=True
)
print(pivot16)

# Extract revenue generated by a specific movie on a specific platform.
pivot17 = pd.pivot_table(
    df,
    values="Revenue_Lakhs",
    index="Movie",
    columns="Platform",
    aggfunc="sum",
    margins=True
)
print(pivot17)

# Sort the multi-index pivot table by revenue (highest first)

pivot18 = pd.pivot_table(
    df,
    values="Revenue_Lakhs",
    index=["Movie", "Platform"],
    aggfunc="sum"
).sort_values("Revenue_Lakhs", ascending=False)
print(pivot18)

# Find the top 3 (Movie, Platform) combinations based on revenue

pivot19 = pd.pivot_table(
    df,
    values="Revenue_Lakhs",
    index="Movie",
    columns="Platform",
    aggfunc="sum",
    margins=True
)
print(pivot19.head(3))
#
# pivot20 = pd.pivot_table(
#     df,
#     values="Revenue_Lakhs",
#     index=["Movie", "Platform"],
#     aggfunc="sum"
# )
#
# print("\n Best Platform for Each Movie")
#
# # Convert multi-index to normal dataframe
# temp = pivot20.reset_index()
#
# # Get row with maximum revenue for each movie
# best_platform = temp.loc[
#     temp.groupby("Movie")["Revenue_Lakhs"].idxmax()
# ]
#
# print(best_platform)

