import pandas as pd
data = {
"Movie": ["KGF", "KGF", "KGF", "Pushpa", "Pushpa", "Pushpa",
         "Dangal", "Dangal", "Dangal", "Jawan", "Jawan", "Jawan"],

"Genre": ["Action", "Action", "Action",
          "Action", "Action", "Action",
          "Drama", "Drama", "Drama",
          "Action", "Action", "Action"],

"Platform": ["Netflix", "Amazon", "Hotstar",
             "Netflix", "Amazon", "Hotstar",
             "Netflix", "Amazon", "Hotstar",
             "Netflix", "Amazon", "Hotstar"],

"Year": [2022, 2022, 2022,
         2023, 2023, 2023,
         2021, 2021, 2021,
        2023, 2023, 2023],

"Views Millions": [25, 20, 15,
                  30, 22, 18,
                  28, 24, 19,
                  35, 26, 21],

"Revenue Lakhs": [500, 420, 350,
600, 480, 390,
550, 460, 370,
700, 520, 410]

}

df=pd.DataFrame(data)
print(df)

#Show total revenue generated by each Movie.
print("\n Revenue by each movie ")
pivot1=pd.pivot_table(
    df,
    values="Revenue Lakhs",
    index="Movie",
    aggfunc="sum"
)
print(pivot1)

#Find total views generated by each Platform.
print("\n Views by each platform")
pivot2=pd.pivot_table(
    df,
    values="Views Millions",
    index="Platform",
    aggfunc="sum"
)
print(pivot2)
#Calculate average revenue per Genre.
print("\nCalculate average revenue per Genre.")
pivot3=pd.pivot_table(
    df,
    values="Revenue Lakhs",
    index="Genre",
    aggfunc="mean"
)
print(pivot3)
#Show total revenue per Year.
pivot4=pd.pivot_table(
    df,
    values="Revenue Lakhs",
    index="Year",
    aggfunc="sum",
)
print(pivot4)

#Find total views for each Genre.
pivot5=pd.pivot_table(
    df,
    values="Views Millions",
    index="Genre",
    aggfunc="sum"
)

print(pivot5)

#Sort movies by total revenue in descending order.
pivot6=pd.pivot_table(
    df,
    values="Revenue Lakhs",
    index="Movie",
    aggfunc="sum"
).sort_values("Revenue Lakhs", ascending=False)
print(pivot6)

#Sort platforms by total views in ascending order.
pivot7=pd.pivot_table(
    df,
    values="Views Millions",
    index="Platform",
    aggfunc="sum"
).sort_values("Views Millions",ascending=True)
print(pivot7)
#Find top 3 highest revenue-generating movies.
pivot8=pd.pivot_table(
    df,
    values="Revenue Lakhs",
    index="Movie",
    aggfunc="sum"
)
print(pivot8.head(3))

#Find bottom 2 movies based on total views.
pivot9=pd.pivot_table(
    df,
    values="Views Millions",
    index="Movie",
    aggfunc="sum"
)
print(pivot9.tail(2))

#Sort genres by average revenue (highest first).
pivot10=pd.pivot_table(
    df,
    values="Revenue Lakhs",
    index="Genre",
    aggfunc="mean"
).sort_values("Revenue Lakhs",ascending=False)
print(pivot10)

#Create a pivot table showing revenue by Platform and Genre.
pivot11=pd.pivot_table(
    df,
    values="Revenue Lakhs",
    index="Platform",
    columns="Genre",
    aggfunc="sum"
)
print(pivot11)

#Create a pivot table showing total views by Year and Platform.
pivot12=pd.pivot_table(
    df,
    values="Views Millions",
    index="Year",
    columns="Platform",
    aggfunc="sum"
)
print(pivot12)
#Create a pivot table showing average revenue by Genre and Year.
pivot13=pd.pivot_table(
    df,
    values="Revenue Lakhs",
    index="Genre",
    columns="Year",
    aggfunc="mean",
    fill_value=0
)
print(pivot13)

#Create a pivot table showing revenue by Movie and Platform with margins.
pivot14=pd.pivot_table(
    df,
    values="Revenue Lakhs",
    index="Movie",
    columns="Platform",
    aggfunc="sum",
    margins=True
)
print(pivot14)

#Create a pivot table showing sum and mean revenue per Platform.
pivot15=pd.pivot_table(
    df,
    values="Revenue Lakhs",
    index="Platform",
    aggfunc=["sum","mean"]
)
print(pivot15)

#Create a pivot table with index as (Movie, Platform) and calculate total revenue.
pivot16=pd.pivot_table(
    df,
    values="Revenue Lakhs",
    index=["Movie","Platform"],
    aggfunc="sum",
    margins=True
)
print(pivot16)

#Extract revenue generated by a specific movie on a specific platform.
pivot17 = pd.pivot_table(
    df,
    values="Revenue Lakhs",
    index="Movie",
    columns="Platform",
    aggfunc="sum"
)
print(pivot17.loc["Jawan", "Netflix"])

#Sort the multi-index pivot table by revenue (highest first).
pivot18 = pd.pivot_table(
    df,
    values="Revenue Lakhs",
    index=["Platform", "Genre"],
    aggfunc="sum"
).sort_values("Revenue Lakhs",ascending=False)
print(pivot18)

#Find the top 3 (Movie, Platform) combinations based on revenue.
pivot19=pd.pivot_table(
    df,
    values="Revenue Lakhs",
    index=["Movie","Platform"],
    aggfunc="sum"
)
print(pivot19.head(3))

#Find which platform performs best for each movie.
pivot20 = pd.pivot_table(
    df,
    values="Revenue Lakhs",
    index="Movie",
    columns="Platform",
    aggfunc="sum"
)
print(pivot20)

#Find total revenue for Action movies only.
pivot21 = pd.pivot_table(
    df,
    values="Revenue Lakhs",
    index="Genre",
    aggfunc="sum",

)
print(pivot21.loc["Action"])
#Find total views in the year 2023 only.
pivot22 = pd.pivot_table(
    df,
    values="Views Millions",
    index="Year",
    aggfunc="sum",
)
print(pivot22.loc[2023])
#23
pivot_action = pd.pivot_table(
        df,
    values="Revenue Lakhs",
    index=["Platform","Genre"],
    aggfunc="sum"
).sort_values("Revenue Lakhs",ascending=False).head(2)
print(pivot_action)
#24
pivot_2023 = pd.pivot_table(
    df,
    values="Revenue Lakhs",
    index="Movie",
    aggfunc="sum"
).sort_values("Revenue Lakhs",ascending=False).head(3)
#25
print(pivot_2023)
pivot_avg_2023 = pd.pivot_table(
    df,
    values="Revenue Lakhs",
    index="Platform",
    aggfunc="mean"
).sort_values("Revenue Lakhs",ascending=False)

print(pivot_avg_2023)

